### ISSUE TITLE
"You forgot to add the 'CompiledExtractPlugin'"

### ISSUE THREAD

**Issue by onionhammer** [atlassian-labs/compiled#1137] opened 2022-03-07 15:05 UTC
**Describe the bug**
After upgrading from 0.8.0 of  `@compiled/webpack-loader` to 0.8.3 or 0.8.4, I now receive this error

```
Failed to compile.

██████╗ ██████╗ ███╗   ███╗██████╗ ██╗██╗     ███████╗██████╗
██╔════╝██╔═══██╗████╗ ████║██╔══██╗██║██║     ██╔════╝██╔══██╗
██║     ██║   ██║██╔████╔██║██████╔╝██║██║     █████╗  ██║  ██║
██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║██║     ██╔══╝  ██║  ██║
╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ██║███████╗███████╗██████╔╝
 ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚═════╝

  @compiled/webpack-loader

  You forgot to add the 'CompiledExtractPlugin' plugin (i.e `{ plugins: [new CompiledExtractPlugin()] }`), please read https://compiledcssinjs.com/docs/css-extraction-webpack

```

My webpack.config.js **does** have the `CompiledExtractPlugin`. It's essentially a standard react ejected webpack.config.js, plus compiled library, following your docs.

**Expected behavior**
Should continue to work largely as before upgrading from 0.8.0

![image](https://user-images.githubusercontent.com/969938/157060100-e444090f-4997-4656-89af-cf90cded3d29.png)

![image](https://user-images.githubusercontent.com/969938/157060170-5f3880d8-58c9-4605-9422-fc976855a6f8.png)

**Comment by JakeLane** [comment] 2022-03-07 23:00
@hannahkmolloy could this be related to https://github.com/atlassian-labs/compiled/commit/530b52d6b7e776a8a4605797fc84c2a91fee0951 ?

**Comment by hannahkmolloy** [comment] 2022-03-11 04:32
@JakeLane It seems likely. However, I am unable to reproduce. @onionhammer Would you mind posting your whole webpack config please?

**Comment by onionhammer** [comment] 2022-03-11 16:35
Sure @hannahkmolloy , here's a link to a gist

https://gist.github.com/onionhammer/e3495a0da97177c139bb98d1b59d2fb5#file-webpack-config-js

**Comment by hannahkmolloy** [comment] 2022-03-16 04:41
@onionhammer I have found the issue. In version 0.8.1, we updated how we check whether the CompiledExtractPlugin is used, but we didn't consider the case of nested rules - like you have [here](https://gist.github.com/onionhammer/e3495a0da97177c139bb98d1b59d2fb5#file-webpack-config-js-L354). Thanks for raising this bug, I am working on a fix right now.

**Comment by hannahkmolloy** [comment] 2022-03-24 03:17
@onionhammer the fix has been released in v0.8.6 https://github.com/atlassian-labs/compiled/releases/tag/%40compiled%2Fwebpack-loader%400.8.6

**Comment by onionhammer** [comment] 2022-03-24 13:07
@hannahkmolloy 

I'm getting the same issue with 0.8.6;

```


██████╗ ██████╗ ███╗   ███╗██████╗ ██╗██╗     ███████╗██████╗
██╔════╝██╔═══██╗████╗ ████║██╔══██╗██║██║     ██╔════╝██╔══██╗
██║     ██║   ██║██╔████╔██║██████╔╝██║██║     █████╗  ██║  ██║
██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║██║     ██╔══╝  ██║  ██║
╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ██║███████╗███████╗██████╔╝
 ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚═════╝

  @compiled/webpack-loader

  You forgot to add the 'CompiledExtractPlugin' plugin (i.e `{ plugins: [new CompiledExtractPlugin()] }`), please read https://compiledcssinjs.com/docs/css-extraction-webpack
```

**Comment by hannahkmolloy** [comment] 2022-03-31 06:03
Oh damn, sorry! It seems you have uncovered two bugs for us. I think there is another bug with how we check the loader is defined. We simply check if the loader property is equal to `@compiled/webpack-loader` but since you are using require.resolve to load the @compiled/webpack-loader, the loader property will be equal to the path to the loader. I will need to update this check.

**Comment by jcan1995** [comment] 2022-09-26 22:28
Hello, are there any updates on this bug? 
I seem to be getting the same issue following the docs and using @compiled/webpack-loader0.9.2.

**Comment by JakeLane** [comment] 2022-09-26 23:58
Hey @hannahkmolloy , I believe this was patched if I remember correctly. Can you confirm?

**Comment by jcan1995** [comment] 2022-11-22 20:21
"@compiled/webpack-loader": "^0.9.5" raises this error when extract is turned on. 
[Here](https://github.com/jcan1995/compiled-issue1/blob/774113ea31f6fbccff32ed207b4ac5a896b660e8/webpack.config.js#L66) is a simplified project where this can be tested. Just uncomment the `extract` option

**Closed** 2022-12-07 23:45 UTC
Labels: bug 🐛

**Comment by jcan1995** [comment] 2023-01-04 22:34
Still seeing this issue using @compiled/webpack-loader v0.9.7
