### ISSUE TITLE
getting an error when import { css } from '@compiled/react

### ISSUE THREAD

**Issue by cameronbraid** [atlassian-labs/compiled#731] opened 2021-04-14 03:58 UTC
```
SyntaxError: /app/src/pages/Compiled.tsx: CallExpression isn't a supported CSS type - try using an object or string. (This is an error on an internal node. Probably an internal
error. Location has been estimated.)
  4 | import { css } from '@compiled/react';
  5 |
> 6 | const buttonCss = css`
    |                   ^^^
  7 |   border: 1px solid blue;
  8 |   border-radius: 3px;
  9 |   font-size: 10px;
    at File.buildCodeFrameError (/app/node_modules/@babel/core/lib/transformation/file/file.js:240:12)
    at NodePath.buildCodeFrameError (/app/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at Object.buildCodeFrameError (/app/node_modules/@compiled/babel-plugin/src/utils/ast.tsx:77:42)
    at Object.buildCss (/app/node_modules/@compiled/babel-plugin/src/utils/css-builders.tsx:434:9)
    at Object.buildCss (/app/node_modules/@compiled/babel-plugin/src/utils/css-builders.tsx:360:20)
    at Object.visitCssPropPath (/app/node_modules/@compiled/babel-plugin/src/css-prop/index.tsx:42:21)
    at PluginPass.JSXOpeningElement (/app/node_modules/@compiled/babel-plugin/src/babel-plugin.tsx:216:9)
    at newFn (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:99:18)
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 16:11-18:5
 @ ./.cache/app.js 17:0-52 28:0-70 30:27-40 28:0-70
```

code :

```
import * as React from "react";
import { Layout } from "src/components/Layout";
import { css } from '@compiled/react';

const buttonCss = css`
  border: 1px solid blue;
  border-radius: 3px;
  font-size: 10px;
  font-weight: 500;
  @media screen and (min-width: 300px) {
    border: 1px solid red;
  }
`;

const Compiled = (props:any) => {
  return (
    <Layout >
      <div css={buttonCss}>Hello</div>
    </Layout>
  )
}

export default Compiled

```

versons
```
    "@compiled/babel-plugin": "^0.6.13",
    "@compiled/css-in-js": "^0.4.7",
    "@compiled/react": "^0.6.10",
```

**Comment by cameronbraid** [comment] 2021-04-14 04:03
I should also mention that this project uses

```
    "@storybook/addon-actions": "^6.2.5",
    "@storybook/addon-essentials": "^6.2.5",
    "@storybook/addon-links": "^6.2.5",
    "@storybook/react": "^6.2.5",
```

Which looking in yarn.lock import `@emotion/core` transitively

**Comment by cameronbraid** [comment] 2021-04-14 04:03
And in vscode I get

```
Type 'CSSProps' is not assignable to type 'InterpolationWithTheme<any>'.
  Type 'Properties<string | number, string & {}>' is not assignable to type 'ObjectInterpolation<undefined>'.
    Index signature is missing in type 'Properties<string | number, string & {}>'.ts(2322)
index.d.ts(84, 5): The expected type comes from property 'css' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'
```

wth the above `index.d.ts` coming from @emotion/core

**Comment by pgmanutd** [comment] 2021-04-14 07:33
Hey @cameronbraid, thanks for raising this issue. I can see you have installed both `@compiled/css-in-js` and `@compiled/react`. Just try installing `@compiled/react` only and remove `@compiled/css-in-js`. Have you configured babel plugin or webpack loader?

**Comment by cameronbraid** [comment] 2021-04-14 07:55
Hi, thanks mate, tried uninstalling `@compiled/css-in-js` but that made no difference.

I'm using the babel plugin, in gatsby as per `gatsby-node.ts` :

```
const onCreateBabelConfig = ({ actions }) : void => {
  actions.setBabelPlugin({
    name: require.resolve("@compiled/babel-plugin"),
    options: {
    },
  });
};

export {
  onCreateBabelConfig,
}
```

**Comment by cameronbraid** [comment] 2021-04-14 07:59
I should mention that I can get it to work using the following, but not template strings :( 

```
import { styled } from "@compiled/react"

let HelloButton = styled.div`
  border: 1px solid blue;
  border-radius: 3px;
  font-size: 10px;
  font-weight: 500;
  @media screen and (min-width: 300px) {
    border: 1px solid red;
  }
`

<HelloButton>Hello</HelloButton>

```

**Comment by cameronbraid** [comment] 2021-04-14 09:03
I implemented a standalone repo

https://codesandbox.io/s/infallible-mayer-3i9bi?file=/src/pages/index.js

**Comment by pgmanutd** [comment] 2021-04-14 09:05
> Hi, thanks mate, tried uninstalling `@compiled/css-in-js` but that made no difference.
> 
> I'm using the babel plugin, in gatsby as per `gatsby-node.ts` :
> 
> ```
> const onCreateBabelConfig = ({ actions }) : void => {
>   actions.setBabelPlugin({
>     name: require.resolve("@compiled/babel-plugin"),
>     options: {
>     },
>   });
> };
> 
> export {
>   onCreateBabelConfig,
> }
> ```

Yeah uninstalling `@compiled/css-in-js` won't make any difference actually. I just asked because its quite old and `@compiled/react` is latest one. 

I think `css` is not supported when using as a variable. @madou: You introduced this recently. Any idea whether it works when assigned to a variable?

@cameronbraid: Can you try like this:

```tsx
import * as React from "react";
import { Layout } from "src/components/Layout";
import { css } from '@compiled/react';

const Compiled = (props:any) => {
  return (
    <Layout >
      <div css={css`
        border: 1px solid blue;
        border-radius: 3px;
        font-size: 10px;
        font-weight: 500;
        @media screen and (min-width: 300px) {
          border: 1px solid red;
        }`}>Hello</div>
    </Layout>
  )
}

export default Compiled
```

**Comment by cameronbraid** [comment] 2021-04-14 09:43
I can get it to work with inline `css={css`...`}` https://codesandbox.io/s/magical-rain-ouioh

However the docs say that you can compose css from https://compiledcssinjs.com/docs/api-css

```
import { css } from '@compiled/react';

const largeText = css`
  font-size: 50px;
  color: black;
`;

```

**Comment by pgmanutd** [comment] 2021-04-14 10:07
> I can get it to work with inline `` css={css`...`} `` https://codesandbox.io/s/magical-rain-ouioh
> 
> However the docs say that you can compose css from https://compiledcssinjs.com/docs/api-css
> 
> ```
> import { css } from '@compiled/react';
> 
> const largeText = css`
>   font-size: 50px;
>   color: black;
> `;
> ```

Nice ❤️ @madou: Any idea around this since you just worked on this one recently 🤔

**Comment by madou** [comment] 2021-04-14 13:25
Hi! Nice find. Funnily enough we only tested with importing usages like this, we didn't test when its already in scope. Oops! So - valid bug 👍. 

I've replicated it - will investigate why it's happening and put up a fix (unless anyone wants to beat me 😄).

**Comment by madou** [comment] 2021-12-01 19:51
Hey mate I'll have a look for you today

**Comment by madou** [comment] 2021-12-01 21:24
@onionhammer What's erroring for you? I can't replicate the original error anymore.

**Comment by madou** [comment] 2021-12-01 21:27
For now I'm going to close this issue as https://github.com/atlassian-labs/compiled/issues/801 fixed this original problem. Please update to latest and let us know how you go.

If you still have things erroring feel free to raise an error with a reproducible test case 🙏.

**Closed by madou** 2021-12-01 21:27 UTC
Labels: bug 🐛
